import Head from 'next/head';
import { FunctionComponent } from 'react';

const LoginPage: FunctionComponent = () => {
  return (
    <>
      <Head>
        <title>Login | Comeon Group</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <div>
        <h1>Login Page</h1>
      </div>
    </>
  );
};
export default LoginPage;
