import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home | Comeon Group</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>

      <div className="flex flex-col items-center justify-start gap-2 mx-auto">
        <div className="w-[780px] h-[146px]">
          <Image
            width={780}
            height={146}
            src="/images/logo.svg"
            alt="Comeon Logo"
          />
        </div>

        <div className="w-3/4 py-10 bg-white">
          <form className="flex flex-col items-center justify-center w-full gap-6">
            <label
              htmlFor="email"
              className="relative block text-gray-400 focus-within:text-gray-600"
            >
              <input
                type="text"
                name="email"
                placeholder="Username"
                className="max-w-lg py-2 pl-4 bg-white rounded-sm border-[1px] border-base-100/40 focus:border-base-100/80 input-sm outline-none"
              />
            </label>

            <input
              type="password"
              placeholder="Password"
              className="py-2 pl-4 bg-white rounded-sm border-[1px] border-base-100/40 focus:border-base-100/80 input-sm outline-none"
            />
            <button
              type="submit"
              className="px-10 capitalize btn btn-sm btn-primary"
            >
              Login
            </button>
          </form>
        </div>
      </div>
    </>
  );
};

export default Home;
